name: Create PDF
on: push

jobs:
  lint:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: "20.18.0"
      - run: |
          node -v
          npm install
          node ./index.js
      - uses: actions/upload-artifact@v4
        with:
          name: create-pdf
          path: ./README.pdf
